// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"go.xrstf.de/corel/pkg/lang/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Program",
			pos:  position{line: 7, col: 1, offset: 61},
			expr: &actionExpr{
				pos: position{line: 7, col: 12, offset: 72},
				run: (*parser).callonProgram1,
				expr: &seqExpr{
					pos: position{line: 7, col: 12, offset: 72},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 7, col: 12, offset: 72},
							label: "stmts",
							expr: &zeroOrMoreExpr{
								pos: position{line: 7, col: 18, offset: 78},
								expr: &seqExpr{
									pos: position{line: 7, col: 19, offset: 79},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 7, col: 19, offset: 79},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 7, col: 21, offset: 81},
											name: "Statement",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 33, offset: 93},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 35, offset: 95},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 24, col: 1, offset: 463},
			expr: &actionExpr{
				pos: position{line: 24, col: 14, offset: 476},
				run: (*parser).callonStatement1,
				expr: &labeledExpr{
					pos:   position{line: 24, col: 14, offset: 476},
					label: "expr",
					expr: &ruleRefExpr{
						pos:  position{line: 24, col: 19, offset: 481},
						name: "Expression",
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 28, col: 1, offset: 561},
			expr: &choiceExpr{
				pos: position{line: 28, col: 15, offset: 575},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 28, col: 15, offset: 575},
						run: (*parser).callonExpression2,
						expr: &labeledExpr{
							pos:   position{line: 28, col: 15, offset: 575},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 19, offset: 579},
								name: "Number",
							},
						},
					},
					&actionExpr{
						pos: position{line: 32, col: 5, offset: 706},
						run: (*parser).callonExpression5,
						expr: &labeledExpr{
							pos:   position{line: 32, col: 5, offset: 706},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 9, offset: 710},
								name: "String",
							},
						},
					},
					&actionExpr{
						pos: position{line: 35, col: 5, offset: 803},
						run: (*parser).callonExpression8,
						expr: &labeledExpr{
							pos:   position{line: 35, col: 5, offset: 803},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 35, col: 9, offset: 807},
								name: "Null",
							},
						},
					},
					&actionExpr{
						pos: position{line: 38, col: 5, offset: 894},
						run: (*parser).callonExpression11,
						expr: &labeledExpr{
							pos:   position{line: 38, col: 5, offset: 894},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 9, offset: 898},
								name: "Bool",
							},
						},
					},
					&actionExpr{
						pos: position{line: 41, col: 5, offset: 985},
						run: (*parser).callonExpression14,
						expr: &labeledExpr{
							pos:   position{line: 41, col: 5, offset: 985},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 9, offset: 989},
								name: "Tuple",
							},
						},
					},
					&actionExpr{
						pos: position{line: 44, col: 5, offset: 1079},
						run: (*parser).callonExpression17,
						expr: &labeledExpr{
							pos:   position{line: 44, col: 5, offset: 1079},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 9, offset: 1083},
								name: "Vector",
							},
						},
					},
					&actionExpr{
						pos: position{line: 47, col: 5, offset: 1176},
						run: (*parser).callonExpression20,
						expr: &labeledExpr{
							pos:   position{line: 47, col: 5, offset: 1176},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 47, col: 9, offset: 1180},
								name: "Object",
							},
						},
					},
					&actionExpr{
						pos: position{line: 50, col: 5, offset: 1273},
						run: (*parser).callonExpression23,
						expr: &labeledExpr{
							pos:   position{line: 50, col: 5, offset: 1273},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 9, offset: 1277},
								name: "Symbol",
							},
						},
					},
				},
			},
		},
		{
			name: "Tuple",
			pos:  position{line: 55, col: 1, offset: 1369},
			expr: &actionExpr{
				pos: position{line: 55, col: 10, offset: 1378},
				run: (*parser).callonTuple1,
				expr: &seqExpr{
					pos: position{line: 55, col: 10, offset: 1378},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 55, col: 10, offset: 1378},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 14, offset: 1382},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 16, offset: 1384},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 55, col: 22, offset: 1390},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 55, col: 33, offset: 1401},
							label: "exprs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 39, offset: 1407},
								expr: &seqExpr{
									pos: position{line: 55, col: 40, offset: 1408},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 55, col: 40, offset: 1408},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 55, col: 42, offset: 1410},
											name: "Expression",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 55, offset: 1423},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 55, col: 57, offset: 1425},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Vector",
			pos:  position{line: 71, col: 1, offset: 1733},
			expr: &actionExpr{
				pos: position{line: 71, col: 11, offset: 1743},
				run: (*parser).callonVector1,
				expr: &seqExpr{
					pos: position{line: 71, col: 11, offset: 1743},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 71, col: 11, offset: 1743},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 15, offset: 1747},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 71, col: 17, offset: 1749},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 71, col: 22, offset: 1754},
								expr: &seqExpr{
									pos: position{line: 71, col: 24, offset: 1756},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 71, col: 24, offset: 1756},
											name: "Expression",
										},
										&zeroOrMoreExpr{
											pos: position{line: 71, col: 35, offset: 1767},
											expr: &seqExpr{
												pos: position{line: 71, col: 37, offset: 1769},
												exprs: []any{
													&zeroOrOneExpr{
														pos: position{line: 71, col: 37, offset: 1769},
														expr: &litMatcher{
															pos:        position{line: 71, col: 37, offset: 1769},
															val:        ",",
															ignoreCase: false,
															want:       "\",\"",
														},
													},
													&ruleRefExpr{
														pos:  position{line: 71, col: 42, offset: 1774},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 71, col: 44, offset: 1776},
														name: "Expression",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 71, col: 61, offset: 1793},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 90, col: 1, offset: 2194},
			expr: &actionExpr{
				pos: position{line: 90, col: 11, offset: 2204},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 90, col: 11, offset: 2204},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 90, col: 11, offset: 2204},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 90, col: 15, offset: 2208},
							label: "pairs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 90, col: 21, offset: 2214},
								expr: &seqExpr{
									pos: position{line: 90, col: 22, offset: 2215},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 90, col: 22, offset: 2215},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 90, col: 24, offset: 2217},
											name: "KeyValuePair",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 39, offset: 2232},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 90, col: 41, offset: 2234},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "KeyValuePair",
			pos:  position{line: 106, col: 1, offset: 2499},
			expr: &actionExpr{
				pos: position{line: 106, col: 17, offset: 2515},
				run: (*parser).callonKeyValuePair1,
				expr: &seqExpr{
					pos: position{line: 106, col: 18, offset: 2516},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 106, col: 18, offset: 2516},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 106, col: 22, offset: 2520},
								name: "Symbol",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 29, offset: 2527},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 106, col: 31, offset: 2529},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 106, col: 37, offset: 2535},
								name: "Expression",
							},
						},
					},
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 143, col: 1, offset: 3179},
			expr: &choiceExpr{
				pos: position{line: 143, col: 11, offset: 3189},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 143, col: 11, offset: 3189},
						run: (*parser).callonSymbol2,
						expr: &labeledExpr{
							pos:   position{line: 143, col: 11, offset: 3189},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 15, offset: 3193},
								name: "PathExpression",
							},
						},
					},
					&actionExpr{
						pos: position{line: 146, col: 5, offset: 3310},
						run: (*parser).callonSymbol5,
						expr: &seqExpr{
							pos: position{line: 146, col: 5, offset: 3310},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 146, col: 5, offset: 3310},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 146, col: 9, offset: 3314},
										name: "Variable",
									},
								},
								&labeledExpr{
									pos:   position{line: 146, col: 18, offset: 3323},
									label: "pathExpr",
									expr: &zeroOrMoreExpr{
										pos: position{line: 146, col: 27, offset: 3332},
										expr: &ruleRefExpr{
											pos:  position{line: 146, col: 27, offset: 3332},
											name: "PathExpression",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 155, col: 5, offset: 3626},
						run: (*parser).callonSymbol12,
						expr: &labeledExpr{
							pos:   position{line: 155, col: 5, offset: 3626},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 155, col: 9, offset: 3630},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "PathExpression",
			pos:  position{line: 160, col: 1, offset: 3728},
			expr: &actionExpr{
				pos: position{line: 160, col: 19, offset: 3746},
				run: (*parser).callonPathExpression1,
				expr: &labeledExpr{
					pos:   position{line: 160, col: 19, offset: 3746},
					label: "pathExpr",
					expr: &oneOrMoreExpr{
						pos: position{line: 160, col: 28, offset: 3755},
						expr: &ruleRefExpr{
							pos:  position{line: 160, col: 29, offset: 3756},
							name: "Accessor",
						},
					},
				},
			},
		},
		{
			name: "Accessor",
			pos:  position{line: 171, col: 1, offset: 3953},
			expr: &choiceExpr{
				pos: position{line: 171, col: 13, offset: 3965},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 171, col: 13, offset: 3965},
						run: (*parser).callonAccessor2,
						expr: &seqExpr{
							pos: position{line: 171, col: 13, offset: 3965},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 171, col: 13, offset: 3965},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&labeledExpr{
									pos:   position{line: 171, col: 17, offset: 3969},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 171, col: 21, offset: 3973},
										name: "PathIdentifier",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 174, col: 5, offset: 4081},
						run: (*parser).callonAccessor7,
						expr: &seqExpr{
							pos: position{line: 174, col: 5, offset: 4081},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 174, col: 5, offset: 4081},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&labeledExpr{
									pos:   position{line: 174, col: 9, offset: 4085},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 174, col: 13, offset: 4089},
										name: "Variable",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 177, col: 5, offset: 4187},
						run: (*parser).callonAccessor12,
						expr: &seqExpr{
							pos: position{line: 177, col: 5, offset: 4187},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 177, col: 5, offset: 4187},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 177, col: 9, offset: 4191},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 177, col: 13, offset: 4195},
										name: "String",
									},
								},
								&litMatcher{
									pos:        position{line: 177, col: 20, offset: 4202},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 180, col: 5, offset: 4295},
						run: (*parser).callonAccessor18,
						expr: &seqExpr{
							pos: position{line: 180, col: 5, offset: 4295},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 180, col: 5, offset: 4295},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 180, col: 9, offset: 4299},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 180, col: 13, offset: 4303},
										name: "Variable",
									},
								},
								&litMatcher{
									pos:        position{line: 180, col: 22, offset: 4312},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 183, col: 5, offset: 4405},
						run: (*parser).callonAccessor24,
						expr: &seqExpr{
							pos: position{line: 183, col: 5, offset: 4405},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 183, col: 5, offset: 4405},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 183, col: 9, offset: 4409},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 183, col: 13, offset: 4413},
										name: "Tuple",
									},
								},
								&litMatcher{
									pos:        position{line: 183, col: 19, offset: 4419},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 186, col: 5, offset: 4506},
						run: (*parser).callonAccessor30,
						expr: &seqExpr{
							pos: position{line: 186, col: 5, offset: 4506},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 186, col: 5, offset: 4506},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 186, col: 9, offset: 4510},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 186, col: 13, offset: 4514},
										name: "Integer",
									},
								},
								&litMatcher{
									pos:        position{line: 186, col: 21, offset: 4522},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PathIdentifier",
			pos:  position{line: 191, col: 1, offset: 4606},
			expr: &actionExpr{
				pos: position{line: 191, col: 19, offset: 4624},
				run: (*parser).callonPathIdentifier1,
				expr: &seqExpr{
					pos: position{line: 191, col: 19, offset: 4624},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 191, col: 19, offset: 4624},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 191, col: 28, offset: 4633},
							expr: &charClassMatcher{
								pos:        position{line: 191, col: 28, offset: 4633},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 198, col: 1, offset: 4781},
			expr: &actionExpr{
				pos: position{line: 198, col: 13, offset: 4793},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 198, col: 13, offset: 4793},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 198, col: 13, offset: 4793},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
						&labeledExpr{
							pos:   position{line: 198, col: 17, offset: 4797},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 22, offset: 4802},
								name: "VariableName",
							},
						},
					},
				},
			},
		},
		{
			name: "VariableName",
			pos:  position{line: 202, col: 1, offset: 4869},
			expr: &actionExpr{
				pos: position{line: 202, col: 17, offset: 4885},
				run: (*parser).callonVariableName1,
				expr: &seqExpr{
					pos: position{line: 202, col: 17, offset: 4885},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 202, col: 17, offset: 4885},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 202, col: 26, offset: 4894},
							expr: &charClassMatcher{
								pos:        position{line: 202, col: 26, offset: 4894},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 206, col: 1, offset: 4943},
			expr: &actionExpr{
				pos: position{line: 206, col: 15, offset: 4957},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 206, col: 15, offset: 4957},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 206, col: 15, offset: 4957},
							val:        "[a-zA-Z_+/*_%?-]",
							chars:      []rune{'_', '+', '/', '*', '_', '%', '?', '-'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 206, col: 31, offset: 4973},
							expr: &charClassMatcher{
								pos:        position{line: 206, col: 31, offset: 4973},
								val:        "[a-zA-Z0-9_+/*_%?-]",
								chars:      []rune{'_', '+', '/', '*', '_', '%', '?', '-'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 213, col: 1, offset: 5128},
			expr: &choiceExpr{
				pos: position{line: 213, col: 9, offset: 5136},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 213, col: 9, offset: 5136},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 213, col: 9, offset: 5136},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 213, col: 56, offset: 5183},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 213, col: 56, offset: 5183},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 215, col: 1, offset: 5231},
			expr: &actionExpr{
				pos: position{line: 215, col: 9, offset: 5239},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 215, col: 9, offset: 5239},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 220, col: 1, offset: 5363},
			expr: &choiceExpr{
				pos: position{line: 220, col: 11, offset: 5373},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 220, col: 11, offset: 5373},
						run: (*parser).callonNumber2,
						expr: &seqExpr{
							pos: position{line: 220, col: 11, offset: 5373},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 220, col: 11, offset: 5373},
									expr: &litMatcher{
										pos:        position{line: 220, col: 11, offset: 5373},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 220, col: 16, offset: 5378},
									name: "Integer",
								},
								&choiceExpr{
									pos: position{line: 220, col: 25, offset: 5387},
									alternatives: []any{
										&seqExpr{
											pos: position{line: 220, col: 27, offset: 5389},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 220, col: 27, offset: 5389},
													val:        ".",
													ignoreCase: false,
													want:       "\".\"",
												},
												&oneOrMoreExpr{
													pos: position{line: 220, col: 31, offset: 5393},
													expr: &ruleRefExpr{
														pos:  position{line: 220, col: 31, offset: 5393},
														name: "DecimalDigit",
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 220, col: 49, offset: 5411},
											name: "Exponent",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 229, col: 5, offset: 5681},
						run: (*parser).callonNumber13,
						expr: &labeledExpr{
							pos:   position{line: 229, col: 5, offset: 5681},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 229, col: 7, offset: 5683},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 233, col: 1, offset: 5732},
			expr: &choiceExpr{
				pos: position{line: 233, col: 12, offset: 5743},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 233, col: 12, offset: 5743},
						run: (*parser).callonInteger2,
						expr: &litMatcher{
							pos:        position{line: 233, col: 12, offset: 5743},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
					},
					&actionExpr{
						pos: position{line: 235, col: 5, offset: 5777},
						run: (*parser).callonInteger4,
						expr: &seqExpr{
							pos: position{line: 235, col: 5, offset: 5777},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 235, col: 5, offset: 5777},
									expr: &litMatcher{
										pos:        position{line: 235, col: 5, offset: 5777},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 235, col: 10, offset: 5782},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 235, col: 30, offset: 5802},
									expr: &ruleRefExpr{
										pos:  position{line: 235, col: 30, offset: 5802},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 244, col: 1, offset: 5970},
			expr: &charClassMatcher{
				pos:        position{line: 244, col: 17, offset: 5986},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 246, col: 1, offset: 5993},
			expr: &charClassMatcher{
				pos:        position{line: 246, col: 24, offset: 6016},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 248, col: 1, offset: 6023},
			expr: &seqExpr{
				pos: position{line: 248, col: 13, offset: 6035},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 248, col: 13, offset: 6035},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 248, col: 18, offset: 6040},
						expr: &charClassMatcher{
							pos:        position{line: 248, col: 18, offset: 6040},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 248, col: 24, offset: 6046},
						expr: &ruleRefExpr{
							pos:  position{line: 248, col: 24, offset: 6046},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 253, col: 1, offset: 6132},
			expr: &actionExpr{
				pos: position{line: 253, col: 11, offset: 6142},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 253, col: 11, offset: 6142},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 253, col: 11, offset: 6142},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 253, col: 15, offset: 6146},
							expr: &choiceExpr{
								pos: position{line: 253, col: 17, offset: 6148},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 253, col: 17, offset: 6148},
										exprs: []any{
											&notExpr{
												pos: position{line: 253, col: 17, offset: 6148},
												expr: &ruleRefExpr{
													pos:  position{line: 253, col: 18, offset: 6149},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 253, col: 30, offset: 6161,
											},
										},
									},
									&seqExpr{
										pos: position{line: 253, col: 34, offset: 6165},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 253, col: 34, offset: 6165},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 253, col: 39, offset: 6170},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 253, col: 57, offset: 6188},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 264, col: 1, offset: 6405},
			expr: &charClassMatcher{
				pos:        position{line: 264, col: 16, offset: 6420},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 266, col: 1, offset: 6436},
			expr: &choiceExpr{
				pos: position{line: 266, col: 19, offset: 6454},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 266, col: 19, offset: 6454},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 266, col: 38, offset: 6473},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 268, col: 1, offset: 6488},
			expr: &charClassMatcher{
				pos:        position{line: 268, col: 21, offset: 6508},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 270, col: 1, offset: 6521},
			expr: &seqExpr{
				pos: position{line: 270, col: 18, offset: 6538},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 270, col: 18, offset: 6538},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 22, offset: 6542},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 31, offset: 6551},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 40, offset: 6560},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 270, col: 49, offset: 6569},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 272, col: 1, offset: 6579},
			expr: &charClassMatcher{
				pos:        position{line: 272, col: 13, offset: 6591},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 277, col: 1, offset: 6670},
			expr: &zeroOrMoreExpr{
				pos: position{line: 277, col: 19, offset: 6688},
				expr: &charClassMatcher{
					pos:        position{line: 277, col: 19, offset: 6688},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 279, col: 1, offset: 6700},
			expr: &notExpr{
				pos: position{line: 279, col: 8, offset: 6707},
				expr: &anyMatcher{
					line: 279, col: 9, offset: 6708,
				},
			},
		},
	},
}

func (c *current) onProgram1(stmts any) (any, error) {
	p := ast.Program{}

	stmtsSl := toAnySlice(stmts)
	if len(stmtsSl) == 0 {
		return p, nil
	}

	for _, stmt := range stmtsSl {
		subSl := toAnySlice(stmt)
		p.Statements = append(p.Statements, subSl[1].(ast.Statement))
	}

	return p, nil
}

func (p *parser) callonProgram1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProgram1(stack["stmts"])
}

func (c *current) onStatement1(expr any) (any, error) {
	return ast.Statement{Expression: expr.(ast.Expression)}, nil
}

func (p *parser) callonStatement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatement1(stack["expr"])
}

func (c *current) onExpression2(val any) (any, error) {
	data, _ := val.(ast.Number)
	fmt.Printf("num: %#v\n", data)
	return ast.Expression{NumberNode: &data}, nil
}

func (p *parser) callonExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression2(stack["val"])
}

func (c *current) onExpression5(val any) (any, error) {
	data, _ := val.(ast.String)
	return ast.Expression{StringNode: &data}, nil
}

func (p *parser) callonExpression5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression5(stack["val"])
}

func (c *current) onExpression8(val any) (any, error) {
	data, _ := val.(ast.Null)
	return ast.Expression{NullNode: &data}, nil
}

func (p *parser) callonExpression8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression8(stack["val"])
}

func (c *current) onExpression11(val any) (any, error) {
	data, _ := val.(ast.Bool)
	return ast.Expression{BoolNode: &data}, nil
}

func (p *parser) callonExpression11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression11(stack["val"])
}

func (c *current) onExpression14(val any) (any, error) {
	data, _ := val.(ast.Tuple)
	return ast.Expression{TupleNode: &data}, nil
}

func (p *parser) callonExpression14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression14(stack["val"])
}

func (c *current) onExpression17(val any) (any, error) {
	data, _ := val.(ast.Vector)
	return ast.Expression{VectorNode: &data}, nil
}

func (p *parser) callonExpression17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression17(stack["val"])
}

func (c *current) onExpression20(val any) (any, error) {
	data, _ := val.(ast.Object)
	return ast.Expression{ObjectNode: &data}, nil
}

func (p *parser) callonExpression20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression20(stack["val"])
}

func (c *current) onExpression23(val any) (any, error) {
	data, _ := val.(ast.Symbol)
	return ast.Expression{SymbolNode: &data}, nil
}

func (p *parser) callonExpression23() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression23(stack["val"])
}

func (c *current) onTuple1(ident, exprs any) (any, error) {
	t := ast.Tuple{Identifier: ident.(ast.Identifier)}

	exprsSl := toAnySlice(exprs)
	if len(exprsSl) == 0 {
		return t, nil
	}

	for _, expr := range exprsSl {
		subSl := toAnySlice(expr)
		t.Expressions = append(t.Expressions, subSl[1].(ast.Expression))
	}

	return t, nil
}

func (p *parser) callonTuple1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTuple1(stack["ident"], stack["exprs"])
}

func (c *current) onVector1(vals any) (any, error) {
	vector := ast.Vector{}

	valsSl := toAnySlice(vals)
	if len(valsSl) == 0 {
		return vector, nil
	}

	vector.Expressions = append(vector.Expressions, valsSl[0].(ast.Expression))

	restSl := toAnySlice(valsSl[1])
	for _, v := range restSl {
		vSl := toAnySlice(v)
		vector.Expressions = append(vector.Expressions, vSl[2].(ast.Expression))
	}

	return vector, nil
}

func (p *parser) callonVector1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVector1(stack["vals"])
}

func (c *current) onObject1(pairs any) (any, error) {
	o := ast.Object{}

	pairsSl := toAnySlice(pairs)
	if len(pairsSl) == 0 {
		return o, nil
	}

	for _, pair := range pairsSl {
		pairSl := toAnySlice(pair)
		o.Data = append(o.Data, pairSl[1].(ast.KeyValuePair))
	}

	return o, nil
}

func (p *parser) callonObject1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["pairs"])
}

func (c *current) onKeyValuePair1(key, value any) (any, error) {
	return ast.KeyValuePair{
		Key:   key.(ast.Symbol),
		Value: value.(ast.Expression),
	}, nil
}

func (p *parser) callonKeyValuePair1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyValuePair1(stack["key"], stack["value"])
}

func (c *current) onSymbol2(val any) (any, error) {
	pathExpr, _ := val.(ast.PathExpression)
	return ast.Symbol{PathExpression: &pathExpr}, nil
}

func (p *parser) callonSymbol2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol2(stack["val"])
}

func (c *current) onSymbol5(val, pathExpr any) (any, error) {
	var expr *ast.PathExpression
	if pathExprSl := toAnySlice(pathExpr); pathExprSl != nil {
		exp := pathExprSl[0].(ast.PathExpression)
		expr = &exp
	}

	variable, _ := val.(ast.Variable)
	return ast.Symbol{Variable: &variable, PathExpression: expr}, nil
}

func (p *parser) callonSymbol5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol5(stack["val"], stack["pathExpr"])
}

func (c *current) onSymbol12(val any) (any, error) {
	ident, _ := val.(ast.Identifier)
	return ast.Symbol{Identifier: &ident}, nil
}

func (p *parser) callonSymbol12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol12(stack["val"])
}

func (c *current) onPathExpression1(pathExpr any) (any, error) {
	path := ast.PathExpression{}
	steps := toAnySlice(pathExpr)

	for i := range steps {
		path.Steps = append(path.Steps, steps[i].(ast.Accessor))
	}

	return path, nil
}

func (p *parser) callonPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathExpression1(stack["pathExpr"])
}

func (c *current) onAccessor2(val any) (any, error) {
	asserted := val.(ast.Identifier)
	return ast.Accessor{Identifier: &asserted}, nil
}

func (p *parser) callonAccessor2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor2(stack["val"])
}

func (c *current) onAccessor7(val any) (any, error) {
	asserted := val.(ast.Variable)
	return ast.Accessor{Variable: &asserted}, nil
}

func (p *parser) callonAccessor7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor7(stack["val"])
}

func (c *current) onAccessor12(val any) (any, error) {
	asserted := val.(ast.String)
	return ast.Accessor{StringNode: &asserted}, nil
}

func (p *parser) callonAccessor12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor12(stack["val"])
}

func (c *current) onAccessor18(val any) (any, error) {
	asserted := val.(ast.Variable)
	return ast.Accessor{Variable: &asserted}, nil
}

func (p *parser) callonAccessor18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor18(stack["val"])
}

func (c *current) onAccessor24(val any) (any, error) {
	asserted := val.(ast.Tuple)
	return ast.Accessor{Tuple: &asserted}, nil
}

func (p *parser) callonAccessor24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor24(stack["val"])
}

func (c *current) onAccessor30(val any) (any, error) {
	asserted := val.(int64)
	return ast.Accessor{Integer: &asserted}, nil
}

func (p *parser) callonAccessor30() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor30(stack["val"])
}

func (c *current) onPathIdentifier1() (any, error) {
	return ast.Identifier{Name: string(c.text)}, nil
}

func (p *parser) callonPathIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathIdentifier1()
}

func (c *current) onVariable1(name any) (any, error) {
	return ast.Variable{Name: name.(string)}, nil
}

func (p *parser) callonVariable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1(stack["name"])
}

func (c *current) onVariableName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonVariableName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariableName1()
}

func (c *current) onIdentifier1() (any, error) {
	return ast.Identifier{Name: string(c.text)}, nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onBool2() (any, error) {
	return ast.Bool{Value: true}, nil
}

func (p *parser) callonBool2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (any, error) {
	return ast.Bool{Value: false}, nil
}

func (p *parser) callonBool4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNull1() (any, error) {
	return ast.Null{}, nil
}

func (p *parser) callonNull1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onNumber2() (any, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	value, err := strconv.ParseFloat(string(c.text), 64)
	if err != nil {
		return nil, err // should never happen
	}

	return ast.Number{Value: value}, nil
}

func (p *parser) callonNumber2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber2()
}

func (c *current) onNumber13(i any) (any, error) {
	return ast.Number{Value: i}, nil
}

func (p *parser) callonNumber13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber13(stack["i"])
}

func (c *current) onInteger2() (any, error) {
	return int64(0), nil
}

func (p *parser) callonInteger2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger2()
}

func (c *current) onInteger4() (any, error) {
	value, err := strconv.ParseInt(string(c.text), 10, 64)
	if err != nil {
		return nil, err // should never happen
	}

	return value, nil
}

func (p *parser) callonInteger4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger4()
}

func (c *current) onString1() (any, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)

	unquoted, err := strconv.Unquote(string(c.text))
	if err != nil {
		return nil, err
	}

	return ast.String{Value: unquoted}, nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
