// Code generated by pigeon; DO NOT EDIT.

// SPDX-FileCopyrightText: 2024 Christoph Mewes
// SPDX-License-Identifier: MIT

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"go.xrstf.de/rudi/pkg/lang/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Program",
			pos:  position{line: 10, col: 1, offset: 141},
			expr: &actionExpr{
				pos: position{line: 10, col: 12, offset: 152},
				run: (*parser).callonProgram1,
				expr: &seqExpr{
					pos: position{line: 10, col: 12, offset: 152},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 10, col: 12, offset: 152},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 10, col: 15, offset: 155},
							label: "stmt",
							expr: &ruleRefExpr{
								pos:  position{line: 10, col: 20, offset: 160},
								name: "Statement",
							},
						},
						&labeledExpr{
							pos:   position{line: 10, col: 30, offset: 170},
							label: "stmts",
							expr: &zeroOrMoreExpr{
								pos: position{line: 10, col: 36, offset: 176},
								expr: &seqExpr{
									pos: position{line: 10, col: 37, offset: 177},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 10, col: 37, offset: 177},
											name: "___",
										},
										&ruleRefExpr{
											pos:  position{line: 10, col: 41, offset: 181},
											name: "Statement",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 53, offset: 193},
							name: "__",
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 56, offset: 196},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 31, col: 1, offset: 671},
			expr: &actionExpr{
				pos: position{line: 31, col: 14, offset: 684},
				run: (*parser).callonStatement1,
				expr: &labeledExpr{
					pos:   position{line: 31, col: 14, offset: 684},
					label: "expr",
					expr: &ruleRefExpr{
						pos:  position{line: 31, col: 19, offset: 689},
						name: "Expression",
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 36, col: 1, offset: 808},
			expr: &choiceExpr{
				pos: position{line: 36, col: 15, offset: 822},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 36, col: 15, offset: 822},
						name: "Vector",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 24, offset: 831},
						name: "Object",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 33, offset: 840},
						name: "Tuple",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 41, offset: 848},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 50, offset: 857},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 59, offset: 866},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 66, offset: 873},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 73, offset: 880},
						name: "Symbol",
					},
					&ruleRefExpr{
						pos:  position{line: 36, col: 82, offset: 889},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "ScalarExpression",
			pos:  position{line: 39, col: 1, offset: 981},
			expr: &choiceExpr{
				pos: position{line: 39, col: 21, offset: 1001},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 39, col: 21, offset: 1001},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 30, offset: 1010},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 39, offset: 1019},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 46, offset: 1026},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 53, offset: 1033},
						name: "Tuple",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 61, offset: 1041},
						name: "Symbol",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 70, offset: 1050},
						name: "Identifier",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 83, offset: 1063},
						name: "ObjectWithPathExpression",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 110, offset: 1090},
						name: "VectorWithPathExpression",
					},
				},
			},
		},
		{
			name: "Tuple",
			pos:  position{line: 44, col: 1, offset: 1186},
			expr: &actionExpr{
				pos: position{line: 44, col: 10, offset: 1195},
				run: (*parser).callonTuple1,
				expr: &seqExpr{
					pos: position{line: 44, col: 10, offset: 1195},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 44, col: 10, offset: 1195},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 14, offset: 1199},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 44, col: 17, offset: 1202},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 22, offset: 1207},
								name: "Expression",
							},
						},
						&labeledExpr{
							pos:   position{line: 44, col: 33, offset: 1218},
							label: "exprs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 44, col: 39, offset: 1224},
								expr: &seqExpr{
									pos: position{line: 44, col: 40, offset: 1225},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 44, col: 40, offset: 1225},
											name: "___",
										},
										&ruleRefExpr{
											pos:  position{line: 44, col: 44, offset: 1229},
											name: "Expression",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 57, offset: 1242},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 44, col: 60, offset: 1245},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&labeledExpr{
							pos:   position{line: 44, col: 64, offset: 1249},
							label: "path",
							expr: &zeroOrOneExpr{
								pos: position{line: 44, col: 69, offset: 1254},
								expr: &ruleRefExpr{
									pos:  position{line: 44, col: 69, offset: 1254},
									name: "AnyQualifiedPathExpression",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VectorItemSeparator",
			pos:  position{line: 70, col: 1, offset: 1792},
			expr: &choiceExpr{
				pos: position{line: 70, col: 24, offset: 1815},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 70, col: 25, offset: 1816},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 70, col: 25, offset: 1816},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 70, col: 28, offset: 1819},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
							&ruleRefExpr{
								pos:  position{line: 70, col: 32, offset: 1823},
								name: "__",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 38, offset: 1829},
						name: "___",
					},
				},
			},
		},
		{
			name: "Vector",
			pos:  position{line: 72, col: 1, offset: 1834},
			expr: &actionExpr{
				pos: position{line: 72, col: 11, offset: 1844},
				run: (*parser).callonVector1,
				expr: &seqExpr{
					pos: position{line: 72, col: 11, offset: 1844},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 72, col: 11, offset: 1844},
							label: "vec",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 15, offset: 1848},
								name: "vector",
							},
						},
						&labeledExpr{
							pos:   position{line: 72, col: 22, offset: 1855},
							label: "path",
							expr: &zeroOrOneExpr{
								pos: position{line: 72, col: 27, offset: 1860},
								expr: &ruleRefExpr{
									pos:  position{line: 72, col: 27, offset: 1860},
									name: "VectorQualifiedPathExpression",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VectorWithPathExpression",
			pos:  position{line: 83, col: 1, offset: 2063},
			expr: &actionExpr{
				pos: position{line: 83, col: 29, offset: 2091},
				run: (*parser).callonVectorWithPathExpression1,
				expr: &seqExpr{
					pos: position{line: 83, col: 29, offset: 2091},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 83, col: 29, offset: 2091},
							label: "vec",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 33, offset: 2095},
								name: "vector",
							},
						},
						&labeledExpr{
							pos:   position{line: 83, col: 40, offset: 2102},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 45, offset: 2107},
								name: "VectorQualifiedPathExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "vector",
			pos:  position{line: 92, col: 1, offset: 2278},
			expr: &choiceExpr{
				pos: position{line: 92, col: 11, offset: 2288},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 92, col: 11, offset: 2288},
						run: (*parser).callonvector2,
						expr: &seqExpr{
							pos: position{line: 92, col: 11, offset: 2288},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 92, col: 11, offset: 2288},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 92, col: 15, offset: 2292},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 92, col: 18, offset: 2295},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 92, col: 23, offset: 2300},
										name: "Expression",
									},
								},
								&labeledExpr{
									pos:   position{line: 92, col: 34, offset: 2311},
									label: "exprs",
									expr: &zeroOrMoreExpr{
										pos: position{line: 92, col: 40, offset: 2317},
										expr: &seqExpr{
											pos: position{line: 92, col: 42, offset: 2319},
											exprs: []any{
												&ruleRefExpr{
													pos:  position{line: 92, col: 42, offset: 2319},
													name: "VectorItemSeparator",
												},
												&ruleRefExpr{
													pos:  position{line: 92, col: 62, offset: 2339},
													name: "Expression",
												},
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 92, col: 76, offset: 2353},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 92, col: 79, offset: 2356},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 111, col: 5, offset: 2751},
						run: (*parser).callonvector15,
						expr: &seqExpr{
							pos: position{line: 111, col: 5, offset: 2751},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 111, col: 5, offset: 2751},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 111, col: 9, offset: 2755},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 111, col: 12, offset: 2758},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 118, col: 1, offset: 2870},
			expr: &actionExpr{
				pos: position{line: 118, col: 11, offset: 2880},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 118, col: 11, offset: 2880},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 118, col: 11, offset: 2880},
							label: "obj",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 15, offset: 2884},
								name: "object",
							},
						},
						&labeledExpr{
							pos:   position{line: 118, col: 22, offset: 2891},
							label: "path",
							expr: &zeroOrOneExpr{
								pos: position{line: 118, col: 27, offset: 2896},
								expr: &ruleRefExpr{
									pos:  position{line: 118, col: 27, offset: 2896},
									name: "ObjectQualifiedPathExpression",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ObjectWithPathExpression",
			pos:  position{line: 129, col: 1, offset: 3084},
			expr: &actionExpr{
				pos: position{line: 129, col: 29, offset: 3112},
				run: (*parser).callonObjectWithPathExpression1,
				expr: &seqExpr{
					pos: position{line: 129, col: 29, offset: 3112},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 129, col: 29, offset: 3112},
							label: "obj",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 33, offset: 3116},
								name: "object",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 40, offset: 3123},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 45, offset: 3128},
								name: "ObjectQualifiedPathExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "object",
			pos:  position{line: 138, col: 1, offset: 3284},
			expr: &actionExpr{
				pos: position{line: 138, col: 11, offset: 3294},
				run: (*parser).callonobject1,
				expr: &seqExpr{
					pos: position{line: 138, col: 11, offset: 3294},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 138, col: 11, offset: 3294},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 138, col: 15, offset: 3298},
							label: "pairs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 138, col: 21, offset: 3304},
								expr: &seqExpr{
									pos: position{line: 138, col: 22, offset: 3305},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 138, col: 22, offset: 3305},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 138, col: 25, offset: 3308},
											name: "KeyValuePair",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 138, col: 40, offset: 3323},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 138, col: 43, offset: 3326},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "KeyValuePair",
			pos:  position{line: 154, col: 1, offset: 3595},
			expr: &actionExpr{
				pos: position{line: 154, col: 17, offset: 3611},
				run: (*parser).callonKeyValuePair1,
				expr: &seqExpr{
					pos: position{line: 154, col: 18, offset: 3612},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 154, col: 18, offset: 3612},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 154, col: 22, offset: 3616},
								name: "ScalarExpression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 154, col: 39, offset: 3633},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 154, col: 42, offset: 3636},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 154, col: 48, offset: 3642},
								name: "Expression",
							},
						},
					},
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 164, col: 1, offset: 3847},
			expr: &choiceExpr{
				pos: position{line: 164, col: 11, offset: 3857},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 164, col: 11, offset: 3857},
						run: (*parser).callonSymbol2,
						expr: &seqExpr{
							pos: position{line: 164, col: 11, offset: 3857},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 164, col: 11, offset: 3857},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&labeledExpr{
									pos:   position{line: 164, col: 15, offset: 3861},
									label: "acc",
									expr: &ruleRefExpr{
										pos:  position{line: 164, col: 19, offset: 3865},
										name: "VectorAccessor",
									},
								},
								&labeledExpr{
									pos:   position{line: 164, col: 34, offset: 3880},
									label: "expr",
									expr: &zeroOrOneExpr{
										pos: position{line: 164, col: 39, offset: 3885},
										expr: &ruleRefExpr{
											pos:  position{line: 164, col: 39, offset: 3885},
											name: "AnyQualifiedPathExpression",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 175, col: 5, offset: 4139},
						run: (*parser).callonSymbol10,
						expr: &seqExpr{
							pos: position{line: 175, col: 5, offset: 4139},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 175, col: 5, offset: 4139},
									label: "acc",
									expr: &ruleRefExpr{
										pos:  position{line: 175, col: 9, offset: 4143},
										name: "ObjectAccessor",
									},
								},
								&labeledExpr{
									pos:   position{line: 175, col: 24, offset: 4158},
									label: "expr",
									expr: &zeroOrOneExpr{
										pos: position{line: 175, col: 29, offset: 4163},
										expr: &ruleRefExpr{
											pos:  position{line: 175, col: 29, offset: 4163},
											name: "AnyQualifiedPathExpression",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 186, col: 5, offset: 4417},
						run: (*parser).callonSymbol17,
						expr: &seqExpr{
							pos: position{line: 186, col: 5, offset: 4417},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 186, col: 5, offset: 4417},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 186, col: 9, offset: 4421},
										name: "Variable",
									},
								},
								&labeledExpr{
									pos:   position{line: 186, col: 18, offset: 4430},
									label: "expr",
									expr: &zeroOrOneExpr{
										pos: position{line: 186, col: 23, offset: 4435},
										expr: &ruleRefExpr{
											pos:  position{line: 186, col: 23, offset: 4435},
											name: "AnyQualifiedPathExpression",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 199, col: 5, offset: 4728},
						run: (*parser).callonSymbol24,
						expr: &litMatcher{
							pos:        position{line: 199, col: 5, offset: 4728},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
					},
				},
			},
		},
		{
			name: "AnyQualifiedPathExpression",
			pos:  position{line: 206, col: 1, offset: 4866},
			expr: &actionExpr{
				pos: position{line: 206, col: 31, offset: 4896},
				run: (*parser).callonAnyQualifiedPathExpression1,
				expr: &labeledExpr{
					pos:   position{line: 206, col: 31, offset: 4896},
					label: "pathExpr",
					expr: &oneOrMoreExpr{
						pos: position{line: 206, col: 40, offset: 4905},
						expr: &ruleRefExpr{
							pos:  position{line: 206, col: 41, offset: 4906},
							name: "Accessor",
						},
					},
				},
			},
		},
		{
			name: "ObjectQualifiedPathExpression",
			pos:  position{line: 218, col: 1, offset: 5154},
			expr: &actionExpr{
				pos: position{line: 218, col: 34, offset: 5187},
				run: (*parser).callonObjectQualifiedPathExpression1,
				expr: &seqExpr{
					pos: position{line: 218, col: 34, offset: 5187},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 218, col: 34, offset: 5187},
							label: "begin",
							expr: &ruleRefExpr{
								pos:  position{line: 218, col: 40, offset: 5193},
								name: "ObjectAccessor",
							},
						},
						&labeledExpr{
							pos:   position{line: 218, col: 55, offset: 5208},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 218, col: 60, offset: 5213},
								expr: &ruleRefExpr{
									pos:  position{line: 218, col: 61, offset: 5214},
									name: "Accessor",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "VectorQualifiedPathExpression",
			pos:  position{line: 233, col: 1, offset: 5513},
			expr: &actionExpr{
				pos: position{line: 233, col: 34, offset: 5546},
				run: (*parser).callonVectorQualifiedPathExpression1,
				expr: &seqExpr{
					pos: position{line: 233, col: 34, offset: 5546},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 233, col: 34, offset: 5546},
							label: "begin",
							expr: &ruleRefExpr{
								pos:  position{line: 233, col: 40, offset: 5552},
								name: "VectorAccessor",
							},
						},
						&labeledExpr{
							pos:   position{line: 233, col: 55, offset: 5567},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 233, col: 60, offset: 5572},
								expr: &ruleRefExpr{
									pos:  position{line: 233, col: 61, offset: 5573},
									name: "Accessor",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Accessor",
			pos:  position{line: 246, col: 1, offset: 5821},
			expr: &choiceExpr{
				pos: position{line: 246, col: 13, offset: 5833},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 246, col: 13, offset: 5833},
						name: "ObjectAccessor",
					},
					&ruleRefExpr{
						pos:  position{line: 246, col: 30, offset: 5850},
						name: "VectorAccessor",
					},
				},
			},
		},
		{
			name: "ObjectAccessor",
			pos:  position{line: 248, col: 1, offset: 5866},
			expr: &actionExpr{
				pos: position{line: 248, col: 19, offset: 5884},
				run: (*parser).callonObjectAccessor1,
				expr: &seqExpr{
					pos: position{line: 248, col: 19, offset: 5884},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 248, col: 19, offset: 5884},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 248, col: 23, offset: 5888},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 248, col: 27, offset: 5892},
								name: "PathIdentifier",
							},
						},
					},
				},
			},
		},
		{
			name: "VectorAccessor",
			pos:  position{line: 256, col: 1, offset: 6102},
			expr: &choiceExpr{
				pos: position{line: 256, col: 19, offset: 6120},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 256, col: 19, offset: 6120},
						run: (*parser).callonVectorAccessor2,
						expr: &seqExpr{
							pos: position{line: 256, col: 19, offset: 6120},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 256, col: 19, offset: 6120},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 256, col: 23, offset: 6124},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 256, col: 26, offset: 6127},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 256, col: 31, offset: 6132},
										name: "ScalarExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 256, col: 48, offset: 6149},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 256, col: 51, offset: 6152},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 258, col: 5, offset: 6225},
						run: (*parser).callonVectorAccessor10,
						expr: &seqExpr{
							pos: position{line: 258, col: 5, offset: 6225},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 258, col: 5, offset: 6225},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 258, col: 9, offset: 6229},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 258, col: 12, offset: 6232},
									val:        "?",
									ignoreCase: false,
									want:       "\"?\"",
								},
								&labeledExpr{
									pos:   position{line: 258, col: 16, offset: 6236},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 258, col: 21, offset: 6241},
										name: "Tuple",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 258, col: 27, offset: 6247},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 258, col: 30, offset: 6250},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PathIdentifier",
			pos:  position{line: 263, col: 1, offset: 6415},
			expr: &actionExpr{
				pos: position{line: 263, col: 19, offset: 6433},
				run: (*parser).callonPathIdentifier1,
				expr: &seqExpr{
					pos: position{line: 263, col: 19, offset: 6433},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 263, col: 19, offset: 6433},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 263, col: 28, offset: 6442},
							expr: &charClassMatcher{
								pos:        position{line: 263, col: 28, offset: 6442},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 270, col: 1, offset: 6590},
			expr: &actionExpr{
				pos: position{line: 270, col: 13, offset: 6602},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 270, col: 13, offset: 6602},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 270, col: 13, offset: 6602},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
						&labeledExpr{
							pos:   position{line: 270, col: 17, offset: 6606},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 270, col: 22, offset: 6611},
								name: "VariableName",
							},
						},
					},
				},
			},
		},
		{
			name: "VariableName",
			pos:  position{line: 275, col: 1, offset: 6767},
			expr: &actionExpr{
				pos: position{line: 275, col: 17, offset: 6783},
				run: (*parser).callonVariableName1,
				expr: &seqExpr{
					pos: position{line: 275, col: 17, offset: 6783},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 275, col: 17, offset: 6783},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 275, col: 26, offset: 6792},
							expr: &charClassMatcher{
								pos:        position{line: 275, col: 26, offset: 6792},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 280, col: 1, offset: 6938},
			expr: &actionExpr{
				pos: position{line: 280, col: 15, offset: 6952},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 280, col: 15, offset: 6952},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 280, col: 15, offset: 6952},
							val:        "[a-zA-Z_+/*_%?-]",
							chars:      []rune{'_', '+', '/', '*', '_', '%', '?', '-'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 280, col: 31, offset: 6968},
							expr: &charClassMatcher{
								pos:        position{line: 280, col: 31, offset: 6968},
								val:        "[a-zA-Z0-9_+/*_%?!-]",
								chars:      []rune{'_', '+', '/', '*', '_', '%', '?', '!', '-'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 294, col: 1, offset: 7273},
			expr: &choiceExpr{
				pos: position{line: 294, col: 9, offset: 7281},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 294, col: 9, offset: 7281},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 294, col: 9, offset: 7281},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 294, col: 49, offset: 7321},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 294, col: 49, offset: 7321},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 296, col: 1, offset: 7362},
			expr: &actionExpr{
				pos: position{line: 296, col: 9, offset: 7370},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 296, col: 9, offset: 7370},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 301, col: 1, offset: 7494},
			expr: &choiceExpr{
				pos: position{line: 301, col: 11, offset: 7504},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 301, col: 11, offset: 7504},
						run: (*parser).callonNumber2,
						expr: &seqExpr{
							pos: position{line: 301, col: 11, offset: 7504},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 301, col: 11, offset: 7504},
									expr: &litMatcher{
										pos:        position{line: 301, col: 11, offset: 7504},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 301, col: 16, offset: 7509},
									name: "Integer",
								},
								&choiceExpr{
									pos: position{line: 301, col: 25, offset: 7518},
									alternatives: []any{
										&seqExpr{
											pos: position{line: 301, col: 27, offset: 7520},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 301, col: 27, offset: 7520},
													val:        ".",
													ignoreCase: false,
													want:       "\".\"",
												},
												&oneOrMoreExpr{
													pos: position{line: 301, col: 31, offset: 7524},
													expr: &ruleRefExpr{
														pos:  position{line: 301, col: 31, offset: 7524},
														name: "DecimalDigit",
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 301, col: 49, offset: 7542},
											name: "Exponent",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 310, col: 5, offset: 7812},
						run: (*parser).callonNumber13,
						expr: &labeledExpr{
							pos:   position{line: 310, col: 5, offset: 7812},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 310, col: 7, offset: 7814},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 314, col: 1, offset: 7863},
			expr: &choiceExpr{
				pos: position{line: 314, col: 12, offset: 7874},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 314, col: 12, offset: 7874},
						run: (*parser).callonInteger2,
						expr: &litMatcher{
							pos:        position{line: 314, col: 12, offset: 7874},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
					},
					&actionExpr{
						pos: position{line: 316, col: 5, offset: 7908},
						run: (*parser).callonInteger4,
						expr: &seqExpr{
							pos: position{line: 316, col: 5, offset: 7908},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 316, col: 5, offset: 7908},
									expr: &litMatcher{
										pos:        position{line: 316, col: 5, offset: 7908},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 316, col: 10, offset: 7913},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 316, col: 30, offset: 7933},
									expr: &ruleRefExpr{
										pos:  position{line: 316, col: 30, offset: 7933},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 325, col: 1, offset: 8101},
			expr: &charClassMatcher{
				pos:        position{line: 325, col: 17, offset: 8117},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 327, col: 1, offset: 8124},
			expr: &charClassMatcher{
				pos:        position{line: 327, col: 24, offset: 8147},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 329, col: 1, offset: 8154},
			expr: &seqExpr{
				pos: position{line: 329, col: 13, offset: 8166},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 329, col: 13, offset: 8166},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 329, col: 18, offset: 8171},
						expr: &charClassMatcher{
							pos:        position{line: 329, col: 18, offset: 8171},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 329, col: 24, offset: 8177},
						expr: &ruleRefExpr{
							pos:  position{line: 329, col: 24, offset: 8177},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 334, col: 1, offset: 8263},
			expr: &actionExpr{
				pos: position{line: 334, col: 11, offset: 8273},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 334, col: 11, offset: 8273},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 334, col: 11, offset: 8273},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 334, col: 15, offset: 8277},
							expr: &choiceExpr{
								pos: position{line: 334, col: 17, offset: 8279},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 334, col: 17, offset: 8279},
										exprs: []any{
											&notExpr{
												pos: position{line: 334, col: 17, offset: 8279},
												expr: &ruleRefExpr{
													pos:  position{line: 334, col: 18, offset: 8280},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 334, col: 30, offset: 8292,
											},
										},
									},
									&seqExpr{
										pos: position{line: 334, col: 34, offset: 8296},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 334, col: 34, offset: 8296},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 334, col: 39, offset: 8301},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 334, col: 57, offset: 8319},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 345, col: 1, offset: 8529},
			expr: &charClassMatcher{
				pos:        position{line: 345, col: 16, offset: 8544},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 347, col: 1, offset: 8560},
			expr: &choiceExpr{
				pos: position{line: 347, col: 19, offset: 8578},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 347, col: 19, offset: 8578},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 347, col: 38, offset: 8597},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 349, col: 1, offset: 8612},
			expr: &charClassMatcher{
				pos:        position{line: 349, col: 21, offset: 8632},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 351, col: 1, offset: 8645},
			expr: &seqExpr{
				pos: position{line: 351, col: 18, offset: 8662},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 351, col: 18, offset: 8662},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 351, col: 22, offset: 8666},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 351, col: 31, offset: 8675},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 351, col: 40, offset: 8684},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 351, col: 49, offset: 8693},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 353, col: 1, offset: 8703},
			expr: &charClassMatcher{
				pos:        position{line: 353, col: 13, offset: 8715},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 358, col: 1, offset: 8798},
			expr: &seqExpr{
				pos: position{line: 358, col: 21, offset: 8820},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 358, col: 23, offset: 8822},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 358, col: 23, offset: 8822},
								val:        "#",
								ignoreCase: false,
								want:       "\"#\"",
							},
							&litMatcher{
								pos:        position{line: 358, col: 29, offset: 8828},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 358, col: 35, offset: 8834},
						expr: &seqExpr{
							pos: position{line: 358, col: 37, offset: 8836},
							exprs: []any{
								&notExpr{
									pos: position{line: 358, col: 37, offset: 8836},
									expr: &ruleRefExpr{
										pos:  position{line: 358, col: 38, offset: 8837},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 358, col: 42, offset: 8841,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "___",
			pos:  position{line: 363, col: 1, offset: 8915},
			expr: &oneOrMoreExpr{
				pos: position{line: 363, col: 8, offset: 8922},
				expr: &choiceExpr{
					pos: position{line: 363, col: 10, offset: 8924},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 363, col: 10, offset: 8924},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 363, col: 23, offset: 8937},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 363, col: 29, offset: 8943},
							name: "SingleLineComment",
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 364, col: 1, offset: 8964},
			expr: &zeroOrMoreExpr{
				pos: position{line: 364, col: 7, offset: 8970},
				expr: &choiceExpr{
					pos: position{line: 364, col: 9, offset: 8972},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 364, col: 9, offset: 8972},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 364, col: 22, offset: 8985},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 364, col: 28, offset: 8991},
							name: "SingleLineComment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 365, col: 1, offset: 9012},
			expr: &zeroOrMoreExpr{
				pos: position{line: 365, col: 6, offset: 9017},
				expr: &ruleRefExpr{
					pos:  position{line: 365, col: 6, offset: 9017},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 367, col: 1, offset: 9030},
			expr: &charClassMatcher{
				pos:        position{line: 367, col: 15, offset: 9044},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 368, col: 1, offset: 9052},
			expr: &litMatcher{
				pos:        position{line: 368, col: 8, offset: 9059},
				val:        "\n",
				ignoreCase: false,
				want:       "\"\\n\"",
			},
		},
		{
			name: "EOS",
			pos:  position{line: 369, col: 1, offset: 9064},
			expr: &choiceExpr{
				pos: position{line: 369, col: 8, offset: 9071},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 369, col: 8, offset: 9071},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 369, col: 8, offset: 9071},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 369, col: 10, offset: 9073},
								expr: &ruleRefExpr{
									pos:  position{line: 369, col: 10, offset: 9073},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 369, col: 29, offset: 9092},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 369, col: 35, offset: 9098},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 369, col: 35, offset: 9098},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 369, col: 38, offset: 9101},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 371, col: 1, offset: 9106},
			expr: &notExpr{
				pos: position{line: 371, col: 8, offset: 9113},
				expr: &anyMatcher{
					line: 371, col: 9, offset: 9114,
				},
			},
		},
	},
}

func (c *current) onProgram1(stmt, stmts any) (any, error) {
	p := ast.Program{
		Statements: []ast.Statement{stmt.(ast.Statement)},
	}

	stmtsSl := toAnySlice(stmts)
	if len(stmtsSl) == 0 {
		return p, nil
	}

	for _, stmt := range stmtsSl {
		subSl := toAnySlice(stmt)
		if s, ok := subSl[1].(ast.Statement); ok {
			p.Statements = append(p.Statements, s)
		}
	}

	return p, nil
}

func (p *parser) callonProgram1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProgram1(stack["stmt"], stack["stmts"])
}

func (c *current) onStatement1(expr any) (any, error) {
	return ast.Statement{Expression: expr.(ast.Expression)}, nil
}

func (p *parser) callonStatement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStatement1(stack["expr"])
}

func (c *current) onTuple1(expr, exprs, path any) (any, error) {
	t := ast.Tuple{
		Expressions: []ast.Expression{expr.(ast.Expression)},
	}

	if path != nil {
		asserted := path.(ast.PathExpression)
		t.PathExpression = &asserted
	}

	exprsSl := toAnySlice(exprs)
	if len(exprsSl) == 0 {
		return t, nil
	}

	for _, expr := range exprsSl {
		subSl := toAnySlice(expr)
		t.Expressions = append(t.Expressions, subSl[1].(ast.Expression))
	}

	return t, nil
}

func (p *parser) callonTuple1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTuple1(stack["expr"], stack["exprs"], stack["path"])
}

func (c *current) onVector1(vec, path any) (any, error) {
	vector := vec.(ast.VectorNode)

	if path != nil {
		asserted := path.(ast.PathExpression)
		vector.PathExpression = &asserted
	}

	return vector, nil
}

func (p *parser) callonVector1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVector1(stack["vec"], stack["path"])
}

func (c *current) onVectorWithPathExpression1(vec, path any) (any, error) {
	vector := vec.(ast.VectorNode)

	pathExpr := path.(ast.PathExpression)
	vector.PathExpression = &pathExpr

	return vector, nil
}

func (p *parser) callonVectorWithPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVectorWithPathExpression1(stack["vec"], stack["path"])
}

func (c *current) onvector2(expr, exprs any) (any, error) {
	vector := ast.VectorNode{
		Expressions: []ast.Expression{expr.(ast.Expression)},
	}

	exprsSl := toAnySlice(exprs)
	if len(exprsSl) == 0 {
		return vector, nil
	}

	for _, v := range exprsSl {
		vSl := toAnySlice(v)

		if len(vSl) > 1 {
			vector.Expressions = append(vector.Expressions, vSl[1].(ast.Expression))
		}
	}

	return vector, nil
}

func (p *parser) callonvector2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onvector2(stack["expr"], stack["exprs"])
}

func (c *current) onvector15() (any, error) {
	return ast.VectorNode{}, nil
}

func (p *parser) callonvector15() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onvector15()
}

func (c *current) onObject1(obj, path any) (any, error) {
	o := obj.(ast.ObjectNode)

	if path != nil {
		asserted := path.(ast.PathExpression)
		o.PathExpression = &asserted
	}

	return o, nil
}

func (p *parser) callonObject1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["obj"], stack["path"])
}

func (c *current) onObjectWithPathExpression1(obj, path any) (any, error) {
	o := obj.(ast.ObjectNode)

	pathExpr := path.(ast.PathExpression)
	o.PathExpression = &pathExpr

	return o, nil
}

func (p *parser) callonObjectWithPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectWithPathExpression1(stack["obj"], stack["path"])
}

func (c *current) onobject1(pairs any) (any, error) {
	o := ast.ObjectNode{}

	pairsSl := toAnySlice(pairs)
	if len(pairsSl) == 0 {
		return o, nil
	}

	for _, pair := range pairsSl {
		pairSl := toAnySlice(pair)
		o.Data = append(o.Data, pairSl[1].(ast.KeyValuePair))
	}

	return o, nil
}

func (p *parser) callonobject1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onobject1(stack["pairs"])
}

func (c *current) onKeyValuePair1(key, value any) (any, error) {
	return ast.KeyValuePair{
		Key:   key.(ast.Expression),
		Value: value.(ast.Expression),
	}, nil
}

func (p *parser) callonKeyValuePair1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyValuePair1(stack["key"], stack["value"])
}

func (c *current) onSymbol2(acc, expr any) (any, error) {
	arrAcc := acc.(ast.PathStep)

	pathExpr := ast.PathExpression{}
	if expr != nil {
		pathExpr = expr.(ast.PathExpression)
	}

	pathExpr.Prepend(arrAcc)

	return ast.Symbol{PathExpression: &pathExpr}, nil
}

func (p *parser) callonSymbol2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol2(stack["acc"], stack["expr"])
}

func (c *current) onSymbol10(acc, expr any) (any, error) {
	objAcc := acc.(ast.PathStep)

	pathExpr := ast.PathExpression{}
	if expr != nil {
		pathExpr = expr.(ast.PathExpression)
	}

	pathExpr.Prepend(objAcc)

	return ast.Symbol{PathExpression: &pathExpr}, nil
}

func (p *parser) callonSymbol10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol10(stack["acc"], stack["expr"])
}

func (c *current) onSymbol17(val, expr any) (any, error) {
	variable := val.(ast.Variable)

	var pathExpr *ast.PathExpression
	if expr != nil {
		asserted := expr.(ast.PathExpression)
		pathExpr = &asserted
	}

	return ast.Symbol{
		Variable:       &variable,
		PathExpression: pathExpr,
	}, nil
}

func (p *parser) callonSymbol17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol17(stack["val"], stack["expr"])
}

func (c *current) onSymbol24() (any, error) {
	return ast.Symbol{
		PathExpression: &ast.PathExpression{},
	}, nil
}

func (p *parser) callonSymbol24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol24()
}

func (c *current) onAnyQualifiedPathExpression1(pathExpr any) (any, error) {
	path := ast.PathExpression{}
	steps := toAnySlice(pathExpr)

	for i := range steps {
		path.Steps = append(path.Steps, steps[i].(ast.PathStep))
	}

	return path, nil
}

func (p *parser) callonAnyQualifiedPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnyQualifiedPathExpression1(stack["pathExpr"])
}

func (c *current) onObjectQualifiedPathExpression1(begin, tail any) (any, error) {
	path := ast.PathExpression{
		Steps: []ast.PathStep{begin.(ast.PathStep)},
	}

	steps := toAnySlice(tail)

	for i := range steps {
		path.Steps = append(path.Steps, steps[i].(ast.PathStep))
	}

	return path, nil
}

func (p *parser) callonObjectQualifiedPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectQualifiedPathExpression1(stack["begin"], stack["tail"])
}

func (c *current) onVectorQualifiedPathExpression1(begin, tail any) (any, error) {
	path := ast.PathExpression{
		Steps: []ast.PathStep{begin.(ast.PathStep)},
	}
	steps := toAnySlice(tail)

	for i := range steps {
		path.Steps = append(path.Steps, steps[i].(ast.PathStep))
	}

	return path, nil
}

func (p *parser) callonVectorQualifiedPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVectorQualifiedPathExpression1(stack["begin"], stack["tail"])
}

func (c *current) onObjectAccessor1(val any) (any, error) {
	// re-wrap identifier as string, because identifiers cannot be evaluated
	ident := val.(ast.Identifier)
	expr := ast.String(ident.Name)

	return ast.PathStep{Expression: expr}, nil
}

func (p *parser) callonObjectAccessor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectAccessor1(stack["val"])
}

func (c *current) onVectorAccessor2(expr any) (any, error) {
	return ast.PathStep{Expression: expr.(ast.Expression)}, nil
}

func (p *parser) callonVectorAccessor2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVectorAccessor2(stack["expr"])
}

func (c *current) onVectorAccessor10(expr any) (any, error) {
	return ast.PathStep{Filter: expr.(ast.Expression)}, nil
}

func (p *parser) callonVectorAccessor10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVectorAccessor10(stack["expr"])
}

func (c *current) onPathIdentifier1() (any, error) {
	return ast.Identifier{Name: string(c.text)}, nil
}

func (p *parser) callonPathIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathIdentifier1()
}

func (c *current) onVariable1(name any) (any, error) {
	return ast.Variable(name.(string)), nil
}

func (p *parser) callonVariable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1(stack["name"])
}

func (c *current) onVariableName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonVariableName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariableName1()
}

func (c *current) onIdentifier1() (any, error) {
	name := string(c.text)
	bang := false
	if strings.HasSuffix(name, "!") {
		bang = true
		name = strings.TrimSuffix(name, "!")
	}

	return ast.Identifier{Name: name, Bang: bang}, nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onBool2() (any, error) {
	return ast.Bool(true), nil
}

func (p *parser) callonBool2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (any, error) {
	return ast.Bool(false), nil
}

func (p *parser) callonBool4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNull1() (any, error) {
	return ast.Null{}, nil
}

func (p *parser) callonNull1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onNumber2() (any, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	value, err := strconv.ParseFloat(string(c.text), 64)
	if err != nil {
		return nil, err // should never happen
	}

	return ast.Number{Value: value}, nil
}

func (p *parser) callonNumber2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber2()
}

func (c *current) onNumber13(i any) (any, error) {
	return ast.Number{Value: i}, nil
}

func (p *parser) callonNumber13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber13(stack["i"])
}

func (c *current) onInteger2() (any, error) {
	return int64(0), nil
}

func (p *parser) callonInteger2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger2()
}

func (c *current) onInteger4() (any, error) {
	value, err := strconv.ParseInt(string(c.text), 10, 64)
	if err != nil {
		return nil, err // should never happen
	}

	return value, nil
}

func (p *parser) callonInteger4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger4()
}

func (c *current) onString1() (any, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)

	unquoted, err := strconv.Unquote(string(c.text))
	if err != nil {
		return nil, err
	}

	return ast.String(unquoted), nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
